Add Build Trigger workflow - Fix typos + commit author

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,7 +1,7 @@
 name: Trigger custom cloudbeaver image build
 on:
   schedule:
-    - cron:  '0 10 * * *' # Everyday at 10 AM UTC
+    - cron: "0 10 * * *" # Everyday at 10 AM UTC
   workflow_dispatch:
 env:
   BASE_IMAGE: dbeaver/cloudbeaver
@@ -9,16 +9,18 @@ jobs:
   trigger-build:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-    - name: Update image base
-      run: |
-        latestTag=$(curl -fsSL "https://hub.docker.com/v2/repositories/${{ env.BASE_IMAGE }}/tags/?page_size=1000" | jq -r '.results | .[] | .name' | grep -P '^[0-9]+\.[0-9]+\.[0-9]+$' | head -1)
-        if [ -z "${latestTag}" ]; then
-          echo "Error: Could not get latest tag of ${{ env.BASE_IMAGE }} image! Abort!"
-          exit 1
-        fi
-        sed -Ei "s|FROM dbeaver/cloudbeaver.*|FROM dbeaver/cloudbeaver:${latestTag}|g" Dockerfile && git add Dockerfile
-        git commit -m 'Bump cloudbeaver to 'Bump cloudbeaver version to ${latestTag}"
-        git tag ${latestTag} -m "Release ${latestTag}"
-        git push origin HEAD ${latestTag}
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Update image base
+        run: |
+          latestTag=$(curl -fsSL "https://hub.docker.com/v2/repositories/${{ env.BASE_IMAGE }}/tags/?page_size=1000" | jq -r '.results | .[] | .name' | grep -P '^[0-9]+\.[0-9]+\.[0-9]+$' | head -1)
+          if [ -z "${latestTag}" ]; then
+            echo "Error: Could not get latest tag of ${{ env.BASE_IMAGE }} image! Abort!"
+            exit 1
+          fi
+          sed -Ei "s|FROM dbeaver/cloudbeaver.*|FROM dbeaver/cloudbeaver:${latestTag}|g" Dockerfile && git add Dockerfile
+          git config --global user.email "exo-swf@exoplatform.com"
+          git config --global user.name "exo-swf"
+          git commit -m "Bump cloudbeaver version to ${latestTag}"
+          git tag ${latestTag} -m "Release ${latestTag}"
+          git push origin HEAD ${latestTag}
